@url=http://localhost:3000

### Crear (cuadrado)
POST {{url}}/calculos
Content-Type: application/json

{ "base": 5, "altura": 5 }

### Crear (rectángulo)
POST {{url}}/calculos
Content-Type: application/json

{ "base": 3.5, "altura": 7 }

### Listar cálculos (incluye tipo al vuelo)
GET {{url}}/calculos
